# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thanish/Desktop/galaxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thanish/Desktop/galaxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thanish/Desktop/galaxy/CMakeFiles /home/thanish/Desktop/galaxy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thanish/Desktop/galaxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named galaxy

# Build rule for target.
galaxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galaxy
.PHONY : galaxy

# fast build rule for target.
galaxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/build
.PHONY : galaxy/fast

engine/display_system/Display.o: engine/display_system/Display.cpp.o
.PHONY : engine/display_system/Display.o

# target to build an object file
engine/display_system/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Display.cpp.o
.PHONY : engine/display_system/Display.cpp.o

engine/display_system/Display.i: engine/display_system/Display.cpp.i
.PHONY : engine/display_system/Display.i

# target to preprocess a source file
engine/display_system/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Display.cpp.i
.PHONY : engine/display_system/Display.cpp.i

engine/display_system/Display.s: engine/display_system/Display.cpp.s
.PHONY : engine/display_system/Display.s

# target to generate assembly for a file
engine/display_system/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Display.cpp.s
.PHONY : engine/display_system/Display.cpp.s

engine/display_system/Pixel.o: engine/display_system/Pixel.cpp.o
.PHONY : engine/display_system/Pixel.o

# target to build an object file
engine/display_system/Pixel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Pixel.cpp.o
.PHONY : engine/display_system/Pixel.cpp.o

engine/display_system/Pixel.i: engine/display_system/Pixel.cpp.i
.PHONY : engine/display_system/Pixel.i

# target to preprocess a source file
engine/display_system/Pixel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Pixel.cpp.i
.PHONY : engine/display_system/Pixel.cpp.i

engine/display_system/Pixel.s: engine/display_system/Pixel.cpp.s
.PHONY : engine/display_system/Pixel.s

# target to generate assembly for a file
engine/display_system/Pixel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/display_system/Pixel.cpp.s
.PHONY : engine/display_system/Pixel.cpp.s

engine/event_streamer/AsynchEventStreamer.o: engine/event_streamer/AsynchEventStreamer.cpp.o
.PHONY : engine/event_streamer/AsynchEventStreamer.o

# target to build an object file
engine/event_streamer/AsynchEventStreamer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/AsynchEventStreamer.cpp.o
.PHONY : engine/event_streamer/AsynchEventStreamer.cpp.o

engine/event_streamer/AsynchEventStreamer.i: engine/event_streamer/AsynchEventStreamer.cpp.i
.PHONY : engine/event_streamer/AsynchEventStreamer.i

# target to preprocess a source file
engine/event_streamer/AsynchEventStreamer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/AsynchEventStreamer.cpp.i
.PHONY : engine/event_streamer/AsynchEventStreamer.cpp.i

engine/event_streamer/AsynchEventStreamer.s: engine/event_streamer/AsynchEventStreamer.cpp.s
.PHONY : engine/event_streamer/AsynchEventStreamer.s

# target to generate assembly for a file
engine/event_streamer/AsynchEventStreamer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/AsynchEventStreamer.cpp.s
.PHONY : engine/event_streamer/AsynchEventStreamer.cpp.s

engine/event_streamer/SyncEventStreamer.o: engine/event_streamer/SyncEventStreamer.cpp.o
.PHONY : engine/event_streamer/SyncEventStreamer.o

# target to build an object file
engine/event_streamer/SyncEventStreamer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/SyncEventStreamer.cpp.o
.PHONY : engine/event_streamer/SyncEventStreamer.cpp.o

engine/event_streamer/SyncEventStreamer.i: engine/event_streamer/SyncEventStreamer.cpp.i
.PHONY : engine/event_streamer/SyncEventStreamer.i

# target to preprocess a source file
engine/event_streamer/SyncEventStreamer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/SyncEventStreamer.cpp.i
.PHONY : engine/event_streamer/SyncEventStreamer.cpp.i

engine/event_streamer/SyncEventStreamer.s: engine/event_streamer/SyncEventStreamer.cpp.s
.PHONY : engine/event_streamer/SyncEventStreamer.s

# target to generate assembly for a file
engine/event_streamer/SyncEventStreamer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/event_streamer/SyncEventStreamer.cpp.s
.PHONY : engine/event_streamer/SyncEventStreamer.cpp.s

engine/game_objects/ColliderObj.o: engine/game_objects/ColliderObj.cpp.o
.PHONY : engine/game_objects/ColliderObj.o

# target to build an object file
engine/game_objects/ColliderObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/ColliderObj.cpp.o
.PHONY : engine/game_objects/ColliderObj.cpp.o

engine/game_objects/ColliderObj.i: engine/game_objects/ColliderObj.cpp.i
.PHONY : engine/game_objects/ColliderObj.i

# target to preprocess a source file
engine/game_objects/ColliderObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/ColliderObj.cpp.i
.PHONY : engine/game_objects/ColliderObj.cpp.i

engine/game_objects/ColliderObj.s: engine/game_objects/ColliderObj.cpp.s
.PHONY : engine/game_objects/ColliderObj.s

# target to generate assembly for a file
engine/game_objects/ColliderObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/ColliderObj.cpp.s
.PHONY : engine/game_objects/ColliderObj.cpp.s

engine/game_objects/GameObj.o: engine/game_objects/GameObj.cpp.o
.PHONY : engine/game_objects/GameObj.o

# target to build an object file
engine/game_objects/GameObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameObj.cpp.o
.PHONY : engine/game_objects/GameObj.cpp.o

engine/game_objects/GameObj.i: engine/game_objects/GameObj.cpp.i
.PHONY : engine/game_objects/GameObj.i

# target to preprocess a source file
engine/game_objects/GameObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameObj.cpp.i
.PHONY : engine/game_objects/GameObj.cpp.i

engine/game_objects/GameObj.s: engine/game_objects/GameObj.cpp.s
.PHONY : engine/game_objects/GameObj.s

# target to generate assembly for a file
engine/game_objects/GameObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameObj.cpp.s
.PHONY : engine/game_objects/GameObj.cpp.s

engine/game_objects/GameState.o: engine/game_objects/GameState.cpp.o
.PHONY : engine/game_objects/GameState.o

# target to build an object file
engine/game_objects/GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameState.cpp.o
.PHONY : engine/game_objects/GameState.cpp.o

engine/game_objects/GameState.i: engine/game_objects/GameState.cpp.i
.PHONY : engine/game_objects/GameState.i

# target to preprocess a source file
engine/game_objects/GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameState.cpp.i
.PHONY : engine/game_objects/GameState.cpp.i

engine/game_objects/GameState.s: engine/game_objects/GameState.cpp.s
.PHONY : engine/game_objects/GameState.s

# target to generate assembly for a file
engine/game_objects/GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/GameState.cpp.s
.PHONY : engine/game_objects/GameState.cpp.s

engine/game_objects/MotionObj.o: engine/game_objects/MotionObj.cpp.o
.PHONY : engine/game_objects/MotionObj.o

# target to build an object file
engine/game_objects/MotionObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/MotionObj.cpp.o
.PHONY : engine/game_objects/MotionObj.cpp.o

engine/game_objects/MotionObj.i: engine/game_objects/MotionObj.cpp.i
.PHONY : engine/game_objects/MotionObj.i

# target to preprocess a source file
engine/game_objects/MotionObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/MotionObj.cpp.i
.PHONY : engine/game_objects/MotionObj.cpp.i

engine/game_objects/MotionObj.s: engine/game_objects/MotionObj.cpp.s
.PHONY : engine/game_objects/MotionObj.s

# target to generate assembly for a file
engine/game_objects/MotionObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/MotionObj.cpp.s
.PHONY : engine/game_objects/MotionObj.cpp.s

engine/game_objects/VisibleObj.o: engine/game_objects/VisibleObj.cpp.o
.PHONY : engine/game_objects/VisibleObj.o

# target to build an object file
engine/game_objects/VisibleObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/VisibleObj.cpp.o
.PHONY : engine/game_objects/VisibleObj.cpp.o

engine/game_objects/VisibleObj.i: engine/game_objects/VisibleObj.cpp.i
.PHONY : engine/game_objects/VisibleObj.i

# target to preprocess a source file
engine/game_objects/VisibleObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/VisibleObj.cpp.i
.PHONY : engine/game_objects/VisibleObj.cpp.i

engine/game_objects/VisibleObj.s: engine/game_objects/VisibleObj.cpp.s
.PHONY : engine/game_objects/VisibleObj.s

# target to generate assembly for a file
engine/game_objects/VisibleObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_objects/VisibleObj.cpp.s
.PHONY : engine/game_objects/VisibleObj.cpp.s

engine/game_server/GameServer.o: engine/game_server/GameServer.cpp.o
.PHONY : engine/game_server/GameServer.o

# target to build an object file
engine/game_server/GameServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_server/GameServer.cpp.o
.PHONY : engine/game_server/GameServer.cpp.o

engine/game_server/GameServer.i: engine/game_server/GameServer.cpp.i
.PHONY : engine/game_server/GameServer.i

# target to preprocess a source file
engine/game_server/GameServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_server/GameServer.cpp.i
.PHONY : engine/game_server/GameServer.cpp.i

engine/game_server/GameServer.s: engine/game_server/GameServer.cpp.s
.PHONY : engine/game_server/GameServer.s

# target to generate assembly for a file
engine/game_server/GameServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/game_server/GameServer.cpp.s
.PHONY : engine/game_server/GameServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... galaxy"
	@echo "... engine/display_system/Display.o"
	@echo "... engine/display_system/Display.i"
	@echo "... engine/display_system/Display.s"
	@echo "... engine/display_system/Pixel.o"
	@echo "... engine/display_system/Pixel.i"
	@echo "... engine/display_system/Pixel.s"
	@echo "... engine/event_streamer/AsynchEventStreamer.o"
	@echo "... engine/event_streamer/AsynchEventStreamer.i"
	@echo "... engine/event_streamer/AsynchEventStreamer.s"
	@echo "... engine/event_streamer/SyncEventStreamer.o"
	@echo "... engine/event_streamer/SyncEventStreamer.i"
	@echo "... engine/event_streamer/SyncEventStreamer.s"
	@echo "... engine/game_objects/ColliderObj.o"
	@echo "... engine/game_objects/ColliderObj.i"
	@echo "... engine/game_objects/ColliderObj.s"
	@echo "... engine/game_objects/GameObj.o"
	@echo "... engine/game_objects/GameObj.i"
	@echo "... engine/game_objects/GameObj.s"
	@echo "... engine/game_objects/GameState.o"
	@echo "... engine/game_objects/GameState.i"
	@echo "... engine/game_objects/GameState.s"
	@echo "... engine/game_objects/MotionObj.o"
	@echo "... engine/game_objects/MotionObj.i"
	@echo "... engine/game_objects/MotionObj.s"
	@echo "... engine/game_objects/VisibleObj.o"
	@echo "... engine/game_objects/VisibleObj.i"
	@echo "... engine/game_objects/VisibleObj.s"
	@echo "... engine/game_server/GameServer.o"
	@echo "... engine/game_server/GameServer.i"
	@echo "... engine/game_server/GameServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

