# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thanish/Desktop/galaxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thanish/Desktop/galaxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thanish/Desktop/galaxy/CMakeFiles /home/thanish/Desktop/galaxy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thanish/Desktop/galaxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named galaxy

# Build rule for target.
galaxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galaxy
.PHONY : galaxy

# fast build rule for target.
galaxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/build
.PHONY : galaxy/fast

engine/ColliderObj.o: engine/ColliderObj.cpp.o
.PHONY : engine/ColliderObj.o

# target to build an object file
engine/ColliderObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/ColliderObj.cpp.o
.PHONY : engine/ColliderObj.cpp.o

engine/ColliderObj.i: engine/ColliderObj.cpp.i
.PHONY : engine/ColliderObj.i

# target to preprocess a source file
engine/ColliderObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/ColliderObj.cpp.i
.PHONY : engine/ColliderObj.cpp.i

engine/ColliderObj.s: engine/ColliderObj.cpp.s
.PHONY : engine/ColliderObj.s

# target to generate assembly for a file
engine/ColliderObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/ColliderObj.cpp.s
.PHONY : engine/ColliderObj.cpp.s

engine/Display.o: engine/Display.cpp.o
.PHONY : engine/Display.o

# target to build an object file
engine/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Display.cpp.o
.PHONY : engine/Display.cpp.o

engine/Display.i: engine/Display.cpp.i
.PHONY : engine/Display.i

# target to preprocess a source file
engine/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Display.cpp.i
.PHONY : engine/Display.cpp.i

engine/Display.s: engine/Display.cpp.s
.PHONY : engine/Display.s

# target to generate assembly for a file
engine/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Display.cpp.s
.PHONY : engine/Display.cpp.s

engine/GameObj.o: engine/GameObj.cpp.o
.PHONY : engine/GameObj.o

# target to build an object file
engine/GameObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameObj.cpp.o
.PHONY : engine/GameObj.cpp.o

engine/GameObj.i: engine/GameObj.cpp.i
.PHONY : engine/GameObj.i

# target to preprocess a source file
engine/GameObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameObj.cpp.i
.PHONY : engine/GameObj.cpp.i

engine/GameObj.s: engine/GameObj.cpp.s
.PHONY : engine/GameObj.s

# target to generate assembly for a file
engine/GameObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameObj.cpp.s
.PHONY : engine/GameObj.cpp.s

engine/GameState.o: engine/GameState.cpp.o
.PHONY : engine/GameState.o

# target to build an object file
engine/GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameState.cpp.o
.PHONY : engine/GameState.cpp.o

engine/GameState.i: engine/GameState.cpp.i
.PHONY : engine/GameState.i

# target to preprocess a source file
engine/GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameState.cpp.i
.PHONY : engine/GameState.cpp.i

engine/GameState.s: engine/GameState.cpp.s
.PHONY : engine/GameState.s

# target to generate assembly for a file
engine/GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/GameState.cpp.s
.PHONY : engine/GameState.cpp.s

engine/MotionObj.o: engine/MotionObj.cpp.o
.PHONY : engine/MotionObj.o

# target to build an object file
engine/MotionObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/MotionObj.cpp.o
.PHONY : engine/MotionObj.cpp.o

engine/MotionObj.i: engine/MotionObj.cpp.i
.PHONY : engine/MotionObj.i

# target to preprocess a source file
engine/MotionObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/MotionObj.cpp.i
.PHONY : engine/MotionObj.cpp.i

engine/MotionObj.s: engine/MotionObj.cpp.s
.PHONY : engine/MotionObj.s

# target to generate assembly for a file
engine/MotionObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/MotionObj.cpp.s
.PHONY : engine/MotionObj.cpp.s

engine/Pixel.o: engine/Pixel.cpp.o
.PHONY : engine/Pixel.o

# target to build an object file
engine/Pixel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Pixel.cpp.o
.PHONY : engine/Pixel.cpp.o

engine/Pixel.i: engine/Pixel.cpp.i
.PHONY : engine/Pixel.i

# target to preprocess a source file
engine/Pixel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Pixel.cpp.i
.PHONY : engine/Pixel.cpp.i

engine/Pixel.s: engine/Pixel.cpp.s
.PHONY : engine/Pixel.s

# target to generate assembly for a file
engine/Pixel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/Pixel.cpp.s
.PHONY : engine/Pixel.cpp.s

engine/VisibleObj.o: engine/VisibleObj.cpp.o
.PHONY : engine/VisibleObj.o

# target to build an object file
engine/VisibleObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/VisibleObj.cpp.o
.PHONY : engine/VisibleObj.cpp.o

engine/VisibleObj.i: engine/VisibleObj.cpp.i
.PHONY : engine/VisibleObj.i

# target to preprocess a source file
engine/VisibleObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/VisibleObj.cpp.i
.PHONY : engine/VisibleObj.cpp.i

engine/VisibleObj.s: engine/VisibleObj.cpp.s
.PHONY : engine/VisibleObj.s

# target to generate assembly for a file
engine/VisibleObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/engine/VisibleObj.cpp.s
.PHONY : engine/VisibleObj.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/galaxy.dir/build.make CMakeFiles/galaxy.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... galaxy"
	@echo "... engine/ColliderObj.o"
	@echo "... engine/ColliderObj.i"
	@echo "... engine/ColliderObj.s"
	@echo "... engine/Display.o"
	@echo "... engine/Display.i"
	@echo "... engine/Display.s"
	@echo "... engine/GameObj.o"
	@echo "... engine/GameObj.i"
	@echo "... engine/GameObj.s"
	@echo "... engine/GameState.o"
	@echo "... engine/GameState.i"
	@echo "... engine/GameState.s"
	@echo "... engine/MotionObj.o"
	@echo "... engine/MotionObj.i"
	@echo "... engine/MotionObj.s"
	@echo "... engine/Pixel.o"
	@echo "... engine/Pixel.i"
	@echo "... engine/Pixel.s"
	@echo "... engine/VisibleObj.o"
	@echo "... engine/VisibleObj.i"
	@echo "... engine/VisibleObj.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

